name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "build.yaml"
      - "config/**"
      - "boards/**"
      - "zephyr/**"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
